overrides:
  - files:
      - '*.ts'
    parser: '@typescript-eslint/parser'
    extends:
      - 'devextreme/typescript'
    rules:
      '@typescript-eslint/no-explicit-any': 'error'
      'import/exports-last': 'error'
